// Package skillruntime bootstraps a configured *lifecycle.Lifecycle from
// .harness/ for B5's skill scripts to use, and exposes helpers for the
// "<sensor-id>:<run-id>" handle format the skills hand to the user.
package skillruntime

import (
	"fmt"
	"strings"
)

// Handle-shape constants.
//
// Sensor IDs are kebab-case slugs per schemas/sensor.yaml (pattern
// `^[a-z][a-z0-9-]*$`, 1-128 chars). Run IDs are ULIDs (26-char
// Crockford base32) generated by lifecycle.defaultRunID().
const (
	sensorIDMinLen = 1
	sensorIDMaxLen = 128
	ulidLen        = 26
)

// ParseHandle splits a "<sensor-id>:<run-id>" string into its components
// and validates that the sensor-id is a kebab-case slug and the run-id
// is a 26-char Crockford base32 ULID.
func ParseHandle(s string) (sensorID, runID string, err error) {
	i := strings.IndexByte(s, ':')
	if i < 0 {
		return "", "", fmt.Errorf("skillruntime: handle missing ':' separator: %q", s)
	}
	sensorID, runID = s[:i], s[i+1:]
	if err := validateSensorIDShape(sensorID); err != nil {
		return "", "", fmt.Errorf("skillruntime: sensor id: %w", err)
	}
	if err := validateULIDShape(runID); err != nil {
		return "", "", fmt.Errorf("skillruntime: run id: %w", err)
	}
	return sensorID, runID, nil
}

// FormatHandle composes "<sensor-id>:<run-id>".
func FormatHandle(sensorID, runID string) string {
	return sensorID + ":" + runID
}

// validateSensorIDShape enforces the kebab-case slug pattern from
// schemas/sensor.yaml: lower-case letter followed by lower-case
// letters, digits, or hyphens. Length 1-128.
func validateSensorIDShape(s string) error {
	if len(s) < sensorIDMinLen || len(s) > sensorIDMaxLen {
		return fmt.Errorf("expected %d-%d chars, got %d (%q)", sensorIDMinLen, sensorIDMaxLen, len(s), s)
	}
	for i, r := range s {
		if i == 0 {
			if !(r >= 'a' && r <= 'z') {
				return fmt.Errorf("must start with lower-case letter, got %q in %q", r, s)
			}
			continue
		}
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9':
		case r == '-':
		default:
			return fmt.Errorf("invalid char %q in %q (allowed: [a-z0-9-])", r, s)
		}
	}
	return nil
}

// validateULIDShape checks length and Crockford base32 alphabet.
// We do NOT parse the timestamp; B2's lifecycle uses oklog/ulid for that
// when it matters. This is a fast structural check at the boundary.
func validateULIDShape(s string) error {
	if len(s) != ulidLen {
		return fmt.Errorf("expected %d chars, got %d (%q)", ulidLen, len(s), s)
	}
	for _, r := range s {
		if !isCrockfordBase32(r) {
			return fmt.Errorf("non-base32 char %q in %q", r, s)
		}
	}
	return nil
}

func isCrockfordBase32(r rune) bool {
	switch {
	case r >= '0' && r <= '9':
		return true
	case r >= 'A' && r <= 'Z' && r != 'I' && r != 'L' && r != 'O' && r != 'U':
		return true
	case r >= 'a' && r <= 'z' && r != 'i' && r != 'l' && r != 'o' && r != 'u':
		return true
	}
	return false
}
